=== jmhr0/Juan-Manuel-Herrera-Ramirez_UD4_LMSGI/Actividad1 ClubNatacion (simil a Librería)/Club/ClubNatacion.dtd
<!ELEMENT Clientes (Cliente*)>
<!ELEMENT Cliente (Apellido1,Apellido2,Nombre,Suscripcion,FechainiDeSub,FechafinDeSub,Sexo)>
<!ELEMENT Apellido1 (#PCDATA)>
<!ELEMENT Apellido2 (#PCDATA)>
<!ELEMENT Nombre (#PCDATA)>
<!ELEMENT Suscripcion (#PCDATA)>
<!ELEMENT FechainiDeSub (#PCDATA)>
<!ELEMENT FechafinDeSub (#PCDATA)>
<!ELEMENT Sexo (#PCDATA)>

=== jmhr0/Juan-Manuel-Herrera-Ramirez_UD4_LMSGI/Actividad1 Librería/ClubNatacion.xml
<?xml version="1.0" encoding = "UTF-8"?>
<!DOCTYPE ClubNatacion SYSTEM "Club/ClubNatacion.dtd">
<!-- <Libreria xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Libreria.xsd"> -->
    <Clientes>
        <Cliente>
            <Apellido1>Herrera</Apellido1>
            <Apellido2>Ramirez</Apellido2>
            <Nombre>Juan Manuel</Nombre>
            <Suscripcion>Vip</Suscripcion>
        <FechainiDeSub>11/01/2023</FechainiDeSub>
        <FechafinDeSub>13/01/2023</FechafinDeSub>
        <Sexo>Hombre</Sexo>
        </Cliente>
    </Clientes>
</Clientes>

=== jmhr0/Juan-Manuel-Herrera-Ramirez_UD4_LMSGI/Actividad1 ClubNatacion (simil a Librería)/ClubNatacion.xml
<?xml version="1.0" encoding = "UTF-8"?>
<!DOCTYPE ClubNatacion SYSTEM "Club/ClubNatacion.dtd">
<!-- <Libreria xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Libreria.xsd"> -->
    <Clientes>
        <Cliente>
            <Apellido1>Herrera</Apellido1>
            <Apellido2>Ramirez</Apellido2>
            <Nombre>Juan Manuel</Nombre>
            <Suscripcion>Vip</Suscripcion>
        <FechainiDeSub>11/01/2023</FechainiDeSub>
        <FechafinDeSub>13/01/2023</FechafinDeSub>
        <Sexo>Hombre</Sexo>
        </Cliente>
        <Cliente>
            <Apellido1>Rodriguez</Apellido1>
            <Apellido2>Mozo</Apellido2>
            <Nombre>Pepe</Nombre>
            <Suscripcion>Premium</Suscripcion>
        <FechainiDeSub>13/01/2023</FechainiDeSub>
        <FechafinDeSub>16/01/2023</FechafinDeSub>
        <Sexo>Hombre</Sexo>
        </Cliente>
        <Cliente>
            <Apellido1>Alfonso</Apellido1>
            <Apellido2>Mozo</Apellido2>
            <Nombre>Juan Miguel</Nombre>
            <Suscripcion>Premium</Suscripcion>
        <FechainiDeSub>13/01/2023</FechainiDeSub>
        <FechafinDeSub>16/01/2023</FechafinDeSub>
        <Sexo>Hombre</Sexo>
        </Cliente>
    </Clientes>
