=== jmhr0/Juan-Manuel-Herrera-Ramirez_UD4_LMSGI/Actividad0 Menus(simil)/CarnesSchema.xsd
<?xml version="1.0" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    version="0.1" xml:lang="es">
    <xs:element name="Carnes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Menus">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="menu" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="componente" type="xs:string" maxOccurs="unbounded"/>
                                        <xs:element name="Calorias" type="xs:integer"/>
                                        <xs:element name="Peso_neto" type="xs:integer"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== jmhr0/Juan-Manuel-Herrera-Ramirez_UD4_LMSGI/Menus(simil a BDsms)/Carnes.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- <!DOCTYPE Menus SYSTEM "Carnes.dtd"> -->
<Carnes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CarnesSchema.xsd">
<Menus>
    <menu nombre="Carrillada" precio="13">
        <componente>Salsa al jugo</componente>
        <componente>patatas</componente>
        <componente>Carne</componente>
        <componente>refresco</componente>
        <Calorias>850</Calorias>
        <Peso_neto>4</Peso_neto>
    </menu>
    <menu nombre="Solomillo al roquefort" precio="8">
        <componente>Lechuga</componente>
        <componente>Cebolla</componente>
        <componente>Salsa de roquefort</componente>
        <componente>Queso</componente>
        <Calorias>950</Calorias>
        <Peso_neto>1</Peso_neto>
    </menu>
 </Menus>
</Carnes>
