=== jmhr0/Juan-Manuel-Herrera-Ramirez_UD4_LMSGI/Actividad4 Clientes/Clientes.dtd
<!ELEMENT Clientes (Sede*)>
<!ELEMENT Sede (Empleado,CodSede,Fecha_alta,Descripcion,Cliente)>
<!ELEMENT Empleado (#PCDATA)>
<!ELEMENT CodSede (#PCDATA)>
<!ELEMENT Fecha_alta (#PCDATA)>
<!ELEMENT Descripcion (#PCDATA)>
<!ELEMENT Cliente (CodCliente,NumVivienda,CosteVivienda,ResumenVivienda,PlazoAltaHacienda)>
<!ELEMENT CodCliente (#PCDATA)>
<!ELEMENT NumVivienda (#PCDATA)>
<!ELEMENT CosteVivienda (#PCDATA)>
<!ELEMENT ResumenVivienda (#PCDATA)>
<!ELEMENT PlazoAltaHacienda (#PCDATA)>

=== jmhr0/Juan-Manuel-Herrera-Ramirez_UD4_LMSGI/Actividad4 Clientes/Clientes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Clientes SYSTEM "Clientes.dtd">

<Clientes>
    <Sede>
        <Cliente>
            <CodCliente></CodCliente>
            <NumVivienda></NumVivienda>
            <CosteVivienda></CosteVivienda>
            <ResumenVivienda></ResumenVivienda>
            <PlazoAltaHacienda></PlazoAltaHacienda>
        </Cliente>
    </Sede>
</Clientes>
