=== jmhr0/Juan-Manuel-Herrera-Ramirez_UD4_LMSGI/Actividad6 (simil)/VentaAgricola.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	
	<xs:element name="VentaAgricola">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Nombre" type="xs:string" />
				<xs:element name="Articulos" type="tipoArticulos" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="tipoArticulos">
		<xs:sequence>
			<xs:element name="género" type="tipoGénero" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="tipoGénero">
		<xs:sequence>
			<xs:element name="Tipo" type="xs:string" />
			<xs:element name="Descripcion" type="xs:string" />
		</xs:sequence>
	</xs:complexType>
	
</xs:schema>

=== jmhr0/Juan-Manuel-Herrera-Ramirez_UD4_LMSGI/Actividad6 (simil)/VentaAgricola.xml
<?xml version="1.0" encoding="UTF-8"?>
<VentaAgricola xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="VentaAgricola.xsd">
       <Nombre>ElChaparral</Nombre>
       <Articulos>
             <género>
                   <Tipo>Semillas</Tipo>
                   <Descripcion>Principios del funcionamiento del lenguaje conocido como java</Descripcion>
             </género>
             <género>
                   <Tipo>Herramientas</Tipo>
                   <Descripcion>Exploración de los diferentes tipos de datos, principalmente arrays</Descripcion>
             </género>
             <género>
                   <Tipo>Maquinaria</Tipo>
                   <Descripcion>Diferentes usos de los paquetes y las clases en el ambito de la programacion</Descripcion>
             </género>
      </Articulos>
</VentaAgricola>
