=== jmhr0/Juan-Manuel-Herrera-Ramirez_UD4_LMSGI/Actividad5 Practicas CFGS/practicascfgsbien.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	
	<xs:element name="DAW">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Alumno" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="NIF" type="tipoNif" />
							<xs:element name="Resultado" type="tipoRes"/>
							<xs:element name="observaciones" type="tipoObs" minOccurs="0"/>
							<xs:choice>
								<xs:element name="ip" type="xs:string" />
								<xs:element name="mac" type="xs:string" />
							</xs:choice>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:simpleType name="tipoNif">
		<xs:restriction base="xs:string">
		</xs:restriction>
	</xs:simpleType>

    <xs:simpleType name="tipoRes">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Apto" />
			<xs:enumeration value="No Apto" />
		</xs:restriction>
    </xs:simpleType>

	<xs:simpleType name="tipoObs">
        <xs:restriction base="xs:string">
        </xs:restriction>
	</xs:simpleType>
	
	
</xs:schema>

=== jmhr0/Juan-Manuel-Herrera-Ramirez_UD4_LMSGI/Actividad5 Practicas CFGS/Practicas CFGS.xml
<?xml version="1.0" encoding="utf-8"?>
<DAW xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="practicascfgsbien.xsd">
	<Alumno>
		<NIF>32183239I</NIF>
		<Resultado>Apto</Resultado>
		<observaciones>Malas notas</observaciones>
		<ip>195.9.0.1</ip>
	</Alumno>
	<Alumno>
		<NIF>32381828X</NIF>
		<Resultado>No Apto</Resultado>
		<observaciones>Falta mucho</observaciones>
		<ip>195.9.0.2</ip>
	</Alumno>
	<Alumno>
		<NIF>19372838Z</NIF>
		<Resultado>No Apto</Resultado>
		<observaciones>Tiene que mejorar en programacion</observaciones>
		<mac>00:1B:44:11:3A:B7</mac>
	</Alumno>
	<Alumno>
		<NIF>39283748K</NIF>
		<Resultado>Apto</Resultado>
		<observaciones>Buen estudiante, debe seguir asi</observaciones>
		<mac>00:1C:42:11:7A:P3</mac>
	</Alumno>
</DAW>
