=== jmhr0/Juan-Manuel-Herrera-Ramirez_UD4_LMSGI/Actividad5 Simil/Nasa.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Nasa">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Astronautas">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Astronauta" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="NIF" type="xs:string"/>
                                        <xs:element name="Despegue">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="Valido"/>
                                                    <xs:enumeration value="No Valido"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="Observaciones" type="xs:string" minOccurs="0"/>
                                        <xs:choice>
                                            <xs:sequence>
                                                <xs:element name="CodCohete" type="xs:string"/>
                                                <xs:element name="CodEquipo" type="xs:string"/>
                                            </xs:sequence>
                                        </xs:choice>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        
    </xs:element>
</xs:schema>

=== jmhr0/Juan-Manuel-Herrera-Ramirez_UD4_LMSGI/Actividad5 Simil/Nasa.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="Nasa.dtd" type="application/xml-dtd"?>
<!-- <Nasa xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Nasa.xsd"> -->
<Nasa>
    <Astronautas>
        <Astronauta>
            <NIF>31293284Y</NIF>
            <Despegue>Valido</Despegue>
            <Observaciones>Aguanta la gravedad 0</Observaciones>
            <CodCohete>00000000003</CodCohete>
            <CodEquipo>0052</CodEquipo>
        </Astronauta>
        <Astronauta>
            <NIF>31293284Y</NIF>
            <Despegue>No Valido</Despegue>
            <Observaciones>Le dan vertigo las alturas</Observaciones>
            <CodCohete>00000000004</CodCohete>
            <CodEquipo>0053</CodEquipo>
        </Astronauta>
        <Astronauta>
            <NIF>31293284Y</NIF>
            <Despegue>Valido</Despegue>
            <Observaciones>Tiende a distraerse</Observaciones>
            <CodCohete>00000000005</CodCohete>
            <CodEquipo>0054</CodEquipo>
        </Astronauta>
    </Astronautas>
</Nasa>
