=== jmhr0/Juan-Manuel-Herrera-Ramirez_UD4_LMSGI/Actividad6 ModulosCFGS/Modulos.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	
	<xs:element name="Modulo">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Nombre" type="xs:string" />
				<xs:element name="Contenidos" type="tipoContenidos" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="tipoContenidos">
		<xs:sequence>
			<xs:element name="UnidadDidactica" type="tipoUnidadDidactica" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="tipoUnidadDidactica">
		<xs:sequence>
			<xs:element name="Titulo" type="xs:string" />
			<xs:element name="Descripcion" type="xs:string" />
		</xs:sequence>
	</xs:complexType>
	
</xs:schema>

=== jmhr0/Juan-Manuel-Herrera-Ramirez_UD4_LMSGI/Actividad6 ModulosCFGS/Modulos.xml
<?xml version="1.0" encoding="UTF-8"?>
<Modulo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Modulos.xsd">
       <Nombre>Programacion</Nombre>
       <Contenidos>
             <UnidadDidactica>
                   <Titulo>Java</Titulo>
                   <Descripcion>Principios del funcionamiento del lenguaje conocido como java</Descripcion>
             </UnidadDidactica>
             <UnidadDidactica>
                   <Titulo>Tipos de datos</Titulo>
                   <Descripcion>Exploraci√≥n de los diferentes tipos de datos, principalmente arrays</Descripcion>
             </UnidadDidactica>
             <UnidadDidactica>
                   <Titulo>Paquetes y clases</Titulo>
                   <Descripcion>Diferentes usos de los paquetes y las clases en el ambito de la programacion</Descripcion>
             </UnidadDidactica>
       </Contenidos>
 </Modulo>
