=== jmhr0/Juan-Manuel-Herrera-Ramirez_UD4_LMSGI/Actividad7 Editorial/Editorial.dtd
<!ELEMENT informe (cabecera, tabla)>
<!ELEMENT cabecera (titulo, contenido, descripcion, fecha)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT contenido (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT tabla (region+, trimestre, libros_vendidos)>
<!ELEMENT region (norte | centro | sur)>
<!ELEMENT norte (#PCDATA| tri| librosv)*>
<!ELEMENT centro (#PCDATA|tri| librosv)*>
<!ELEMENT sur (#PCDATA|tri| librosv)*>
<!ELEMENT tri (#PCDATA)>
<!ELEMENT librosv (#PCDATA)>
<!ELEMENT trimestre (#PCDATA)>
<!ELEMENT libros_vendidos (#PCDATA)>

=== jmhr0/Juan-Manuel-Herrera-Ramirez_UD4_LMSGI/Actividad7 Editorial/Editorial.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE informe SYSTEM "Editorial.dtd">
<informe>
  <cabecera>
    <titulo>Ediciones Aranda</titulo>
    <contenido>Informe regional del ventas</contenido>
    <descripcion>Descripcion: informe de ventas para las regiones Norte, Centro y Sur</descripcion>
    <fecha>Fecha: 30/12/2009</fecha>
  </cabecera>
  <tabla>
    <region>
      <norte>
        <tri>1</tri>
        <librosv>24000</librosv>
        <tri>2</tri>
        <librosv>38600</librosv>
        <tri>3</tri>
        <librosv>NO_INFO</librosv>
        <tri>4</tri>
        <librosv>NO_INFO</librosv>
      </norte>
    </region>
    <region>
      <centro>
        <tri>1</tri>
        <librosv>NO_INFO</librosv>
        <tri>2</tri>
        <librosv>16080</librosv>
        <tri>3</tri>
        <librosv>25000</librosv>
        <tri>4</tri>
        <librosv>29000</librosv>
      </centro>
    </region>
    <region>
      <sur>
        <tri>1</tri>
        <librosv>27000</librosv>
        <tri>2</tri>
        <librosv>31400</librosv>
        <tri>3</tri>
        <librosv>40100</librosv>
        <tri>4</tri>
        <librosv>30000</librosv>
      </sur>
    </region>
    <trimestre>Trimestre</trimestre>
    <libros_vendidos>Libros vendidos</libros_vendidos>
  </tabla>
</informe>
